# For technical reasons, this file is *NOT* reloaded automatically when you use 
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juspreet Singh Sandhu
description: >- # this means to ignore newlines until "baseurl:"
  Juspreet Singh Sandhu
baseurl: "/" # the subpath of the site
url: "https://juspreetsandhu.me" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Publications
    - name: Teaching
    - name: Hobbies


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: jus065@g.harvard.edu
      link: mailto:jus065@g.harvard.edu
    - name: Office
      value: SEC 3.319, 150 Western Ave, Boston, MA 02134
      link: https://www.google.com/maps/place/Harvard+John+A.+Paulson+School+Of+Engineering+And+Applied+Sciences/@42.3631937,-71.1294895,17z/data=!4m5!3m4!1s0x89e37741111a2a01:0x69c2a968586f826c!8m2!3d42.3631937!4d-71.1273008
  follow:
    - name: Twitter
      link: http://twitter.com/JuspreetS
      username: "@JuspreetS"
    - name: GitHub
      link: http://github.com/jssandh2

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
