# For technical reasons, this file is *NOT* reloaded automatically when you use 
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juspreet Singh Sandhu
description: >- # this means to ignore newlines until "baseurl:"
  Juspreet Singh Sandhu
baseurl: "/" # the subpath of the site
url: "https://juspreetsandhu.me" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Publications
    - name: Reading Group
    - name: Teaching
    - name: Hobbies


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: jsinghsa@ucsc.edu
      link: mailto:jus065@g.harvard.edu
    - name: Office
      value: E2.489, 1156 High St, Santa Cruz, CA 95064
      link: https://www.google.com/maps/place/Engineering+Building+2+(E2)/@37.0009723,-122.065812,17z/data=!3m1!5s0x808e4174e5066bc9:0x8580897ed8975e00!4m15!1m8!3m7!1s0x808e4174e51cfedb:0x5ec352acda2725ee!2sEngineering+2,+1156+High+St,+Santa+Cruz,+CA+95064!3b1!8m2!3d37.0009723!4d-122.0632371!16s%2Fg%2F12hspf6db!3m5!1s0x808e4174fa049a43:0x9856b16dc93b8cb6!8m2!3d37.0009737!4d-122.0629088!16s%2Fg%2F11btyv70cb?entry=ttu
  follow:
    - name: Twitter
      link: http://twitter.com/JuspreetS
      username: "@JuspreetS"
    - name: GitHub
      link: http://github.com/jssandh2

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
