# For technical reasons, this file is *NOT* reloaded automatically when you use 
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juspreet Singh Sandhu
description: >- # this means to ignore newlines until "baseurl:"
  Juspreet Singh Sandhu
baseurl: "/" # the subpath of the site
url: "https://juspreetsandhu.me" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Research
    - name: Reading Group
    - name: Teaching
    - name: Hobbies


footer:
  show_powered_by: true
  contact:
    - name: Email
      value: js.sandhu@colostate.edu
      link: mailto:js.sandhu@colostate.edu
    - name: Office
      value: Room 376, 456 University Ave, Fort Collins, CO 80521
      link: https://www.google.com/maps/place/Computer+Science+Building/@40.5740652,-105.0859646,16z/data=!3m2!4b1!5s0x87694a571ed5e1e7:0x93ba42de4e2faa60!4m6!3m5!1s0x87694a571e35de97:0x5bd4e0ecf56e3ef1!8m2!3d40.5740612!4d-105.0833897!16s%2Fg%2F11ckthmmqh?entry=ttu&g_ep=EgoyMDI1MDgwNS4wIKXMDSoASAFQAw%3D%3D
  follow:
    - name: Twitter
      link: http://twitter.com/JuspreetS
      username: "@JuspreetS"
    - name: GitHub
      link: http://github.com/jssandh2

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
