# For technical reasons, this file is *NOT* reloaded automatically when you use 
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juspreet Singh Sandhu
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://marwahaha.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: ""

header:
  pages:
    - name: Home
      slug: /
    - name: Blog
    - name: Research Interests
    - name: Publications
    - name: Hobbies

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: jus065@g.harvard.edu
      link: mailto:jus065@g.harvard.edu
  follow:
    - name: Twitter
      link: http://twitter.com/JuspreetS
      username: "@JuspreetS"
    - name: GitHub
      link: http://github.com/jssandh2

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
